- path  : data/transition-config
  url   : git@github.com:alphagov/transition-config.git
- path  : data/transition-stats
  url   : git@github.com:alphagov/transition-stats.git
- path  : data/pre-transition-stats
  url   : git@github.com:alphagov/pre-transition-stats.git
